version: "3.7"

services:
  django_app:
    build: ./django_project
    container_name: django_app
    restart: always
    expose:
      - 8080
    volumes:
      - "./django_project/media:/django_app/media"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./django_project/media:/media"
